# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricereport',
            old_name='created',
            new_name='submitted',
        ),
    ]
